#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014-2016, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
#          José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh

SNAP_ID="$2"
VM_ID="$3"
#HOST="$4"
DOMAIN="one-${VM_ID}"


echo "${SNAP_ID}"

sudo mkdir -p /mnt/backup/lxc/${DOMAIN}/snaps/${SNAP_ID}/disks

#find lv
lvpath=`cat /var/lib/lxc/one-${VM_ID}/config | grep lxc.rootfs | cut -d' ' -f3`
echo "$lvpath" >> /var/lib/one/output
echo "$0 $1 $2 $3 $4 $5 $6" >> /var/lib/one/output
lvsize=`sudo lxc-attach --elevated-privileges -n ${DOMAIN} -- du -sD --exclude /mnt --exclude /proc / | cut -f1`
lvsize=$(($lvsize / 1000 * 1024 + 1000000))
remainder=$(($lvsize % 512))
lvsize=$(($lvsize - $remainder))
sudo lvcreate -L${lvsize}K -s -n ${DOMAIN}-snap-${SNAP_ID} ${lvpath}

sudo mkdir -p /mnt/snap-${DOMAIN}

sudo rsync -zqrtalp /var/lib/lxc/${DOMAIN}/ --exclude=snaps --exclude=rootfs.dev /mnt/backup/lxc/${DOMAIN}/snaps/${SNAP_ID}

sudo mkdir /mnt/empty-dir-snap-${DOMAIN}

echo "$DOMAIN-snap-$SNAP_ID.img f 444 root root dd if=/dev/vg-one/$DOMAIN-snap-$SNAP_ID bs=512 conv=notrunc" >> pseudofile-${DOMAIN}-snap-${SNAP_ID}

sudo mksquashfs /mnt/empty-dir-snap-${DOMAIN} /mnt/backup/lxc/${DOMAIN}/snaps/${SNAP_ID}/disks/${DOMAIN}-snap-${SNAP_ID}-squash.img -pf pseudofile-${DOMAIN}-snap-${SNAP_ID}

sudo rm -f pseudofile-${DOMAIN}-snap-${SNAP_ID}

sudo rm -rf /mnt/empty-dir-snap-${DOMAIN}
sudo rm -rf /mnt/snap-${DOMAIN}
sudo lvremove -f /dev/vg-one/${DOMAIN}-snap-${SNAP_ID}

if [ "$?" = "0" ]; then
    echo "${SNAP_ID}"
else
    error_message "Could not create snapshot $NAME for domain $DOMAIN."
    exit -1
fi

echo "${SNAP_ID}"

exit 0
