#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2014-2016, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Authors: Sergio Vega Gutiérrez          sergiojvg92@gmail.com              #
#          José Manuel de la Fé Herrero   jmdelafe92@gmail.com               #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

#source $(dirname $0)/lxcrc
source $(dirname $0)/../../scripts_common.sh

SNAP_ID="$2"
VM_ID="$3"
DOMAIN="one-$VM_ID"

exec_and_log "sudo lxc-stop -n one-${VM_ID}"

sudo lxc-wait -n one-${VM_ID} -s STOPPED

sudo mkdir -p /mnt/${DOMAIN}-snap-${SNAP_ID}

sudo rsync -zqrtlap /mnt/backup/lxc/${DOMAIN}/snaps/${SNAP_ID}/ --exclude=disks /var/lib/lxc/${DOMAIN}/

lvpath=`cat /var/lib/lxc/one-${VM_ID}/config | grep lxc.rootfs | cut -d' ' -f3`
echo "$lvpath" >> /var/lib/one/output
echo "$1 $2 $3 $4 $5" >> /var/lib/one/output

sudo mount /mnt/backup/lxc/${DOMAIN}/snaps/${SNAP_ID}/disks/${DOMAIN}-snap-${SNAP_ID}-squash.img /mnt/${DOMAIN}-snap-${SNAP_ID}

sudo dd if=/mnt/${DOMAIN}-snap-${SNAP_ID}/${DOMAIN}-snap-${SNAP_ID}.img of=$lvpath bs=512

sudo umount /mnt/${DOMAIN}-snap-${SNAP_ID}/

sudo -E lxc-start -l DEBUG -d -n one-$VM_ID -f /var/lib/lxc/one-$VM_ID/config

if [ "x$?" = "x0" ]; then
    echo "one-$VM_ID"
else
    error_message "Could not create domain from one-$VM_ID"
    exit -1
fi

VM_STATE=$(sudo lxc-info -n one-$VM_ID | grep State | awk '{ print $2 }')
if [ "$VM_STATE" != "RUNNING" ]; then
	sleep 5
	VM_STATE=$(sudo lxc-info -n one-$VM_ID | grep State | awk '{ print $2 }')
	if [ "$VM_STATE" != "RUNNING" ]; then
		sleep 5
		VM_STATE=$(sudo lxc-info -n one-$VM_ID | grep State | awk '{ print $2 }')
		if [ "$VM_STATE" != "RUNNING" ]; then
			exit -1
		fi
	fi
fi

exit 0
